In [1]:
import torch

In [16]:
a = torch.tensor([[[1.0,2.0],[4.0,5.0],[5.0,6.0]],[[1.0,2.0],[4.0,5.0],[5.0,6.0]]])
b = torch.tensor([[1,10],[100,1000]])

In [9]:
m = torch.nn.Linear(2,3)
m(a)

tensor([[[-0.4281,  0.1335, -0.3052],
         [-2.8558,  1.5691, -0.9977],
         [-3.6650,  2.0476, -1.2286]],

        [[-0.4281,  0.1335, -0.3052],
         [-2.8558,  1.5691, -0.9977],
         [-3.6650,  2.0476, -1.2286]]], grad_fn=<ViewBackward0>)

In [17]:
torch.concat([a,a],dim=1)

tensor([[[1., 2.],
         [4., 5.],
         [5., 6.],
         [1., 2.],
         [4., 5.],
         [5., 6.]],

        [[1., 2.],
         [4., 5.],
         [5., 6.],
         [1., 2.],
         [4., 5.],
         [5., 6.]]])

In [14]:
a.shape

torch.Size([2, 3])

In [12]:
a = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])

In [15]:
def adj_to_attn_mask(adj_matrix, pos_inf=False):
    """Assumes adj_matrix is only 0s and 1s"""

    inf = float("inf") if pos_inf else float("-inf")
    attn_mask = torch.zeros_like(adj_matrix.float())
    attn_mask[adj_matrix == 0] = inf

    # Ensure nodes with no connections (fake nodes) don't have all -inf in the attn mask
    # Otherwise we would have problems when softmaxing
    n_nodes = adj_matrix.sum(dim=-1)
    attn_mask[n_nodes == 0] = 0.0

    return attn_mask

In [16]:
mat=torch.tensor([[1,0],[0,1]])
adj_to_attn_mask(mat)

tensor([[0., -inf],
        [-inf, 0.]])

In [9]:
torch.diag(a,dim=1)

TypeError: diag() got an unexpected keyword argument 'dim'

In [30]:
x = torch.randn(2, 5, 4, 2)
(torch.diagonal(a, offset=0, dim1=1, dim2=2)).shape
torch.diagonal(a, offset=0, dim1=1, dim2=0)

tensor([[1, 7],
        [2, 8]])

In [34]:
a = torch.tensor([1,10,100]).unsqueeze(-1)
b = torch.tensor([[1,2],[3,4],[5,6]])
print(a.shape)
print(b.shape)
print((a*b).shape)
print(a*b)

torch.Size([3, 1])
torch.Size([3, 2])
torch.Size([3, 2])
tensor([[  1,   2],
        [ 30,  40],
        [500, 600]])
